# Use root/example as user/password credentials

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./data/docker/volumes/mysql/:/var/lib/mysql