#Spring
spring.application.name=springBootLearn
server.port=8080

#Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Jwt
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000
#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false